azure:
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ${APPLICATION_NAME:ms-audit-sync}
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    primary:
      jdbc-url: ${DB_URL_ADMIN}
      driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 100
        order_inserts: false
        order_updates: false

logging:
  level:
    org.springframework.jdbc.datasource: DEBUG
    org.hibernate.SQL: DEBUG
